### PR TITLE
docs(emoji-key): adding emoji for mentoring

### PR DESCRIPTION
**Pull request by mloning**
✅ Closes: #423

**What**: 
* Adding emoji for mentoring 
* Minor style changes (consistent capitalisation at the beginning)

**Why**: Currently not covered by emoji key

**How**: Adding emoji with description to emoji key documentation

**Checklist**:

- [x] Documentation
- [ ] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Comment by mloning** [comment]
I'm not sure where else I would have to make changes so that the bot and command line tool supports the new emoji.

**Comment by Berkmann18** [comment]
> I'm not sure where else I would have to make changes so that the bot and command line tool supports the new emoji.

You'll need to submit a PR on the relevant repos: https://github.com/all-contributors/all-contributors-cli and https://github.com/all-contributors/all-contributors-bot for that.

**Comment by Berkmann18** [comment]
@all-contributors Please add @mloning for doc

**Comment by mloning** [comment]
@Berkmann18 Could you point me to the files in https://github.com/all-contributors/all-contributors-cli and https://github.com/all-contributors/all-contributors-bot to implement the changes? I'm happy to take a look!

**Comment by Berkmann18** [comment]
@mloning Sure, here they are:
CLI: https://github.com/all-contributors/all-contributors-cli/blob/master/src/util/contribution-types.js
Bot: https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/processIssueComment/utils/parse-comment/index.js

**Pull request merged**
