### PR TITLE
chore: ignore package-lock.json

### PR DESCRIPTION
**Pull request by NotMoni**
Dont accidenty commit package-lock.json to git.

**What**: Add pkg-lock.json to gitignore

**Why**:
This repo uses Yarn

**How**:
.gitignore

**Checklist**:

- [ ] Documentation
- [ x] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Comment by NotMoni** [comment]
@all-contributors please add @NotMoni for infra

**Comment by yg** [comment]
@NotMoni @Berkmann18  I think removing `package-lock.json` is not a good idea! Here is the official doc.

https://docs.npmjs.com/configuring-npm/package-lock-json.html

Screenshot

PS: But in this repo, `package-lock.json` file did not exist, I don't know why?

**Comment by NotMoni** [comment]
Yarn conflicts with pkg-lock.json

**Comment by NotMoni** [comment]
That is why 🦄

**Comment by yg** [comment]
> Yarn conflicts with pkg-lock.json

Oops! Sorry I haven't noticed that!

**Pull request merged**
