### PR TITLE
fix: 🐛 remove typo causing docs i18n deployment issue

### LINKED ISSUE #651: Missing different languages documentation URLs
Missing different languages documentation URLs

**To Reproduce**
1. Go to https://github.com/all-contributors/all-contributors
2. Scroll down to '**Read this documentation in the following languages**'
3. Click on URLs of different documentation
4. See the error

**Screenshots**
image

**Missing URLs**
image

### PR DESCRIPTION
**Pull request by hsyoonhs**
I've noticed a small but critical issue in the `crowdin.yaml` file, which has been present since last year. There is an unnecessary comma that is triggering the following error message during Netlify deployment: `Loading config failed. Please, check your configuration file.` This leads to the failure of the i18n feature, causing all translations to be unavailable on the docs.

To address this problem, I've removed the unnecessary comma, and the deployment issue [seems to be resolved](https://deploy-preview-726--allcontributors-org.netlify.app/docs/ko/overview). This change resolves #651, which was also referenced in issues #143 and #187.

-----

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Review by Berkmann18 — APPROVED** [review]
Amazing! Thank you.

**Comment by Berkmann18** [comment]
@all-contributors please add @hsyoonhs for a bug fix

**Comment by taras-bl** [comment]
NSFW

**Comment by taras-bl** [comment]
NSFW

**Pull request merged**
