### PR TITLE
docs: remove outdated link

### PR DESCRIPTION
**Pull request by skywinder**
**What**:

Fixed outdated example
 Cheers.

**Why**:
because it's outdated

**How**:
update docs.

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [x] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

@all-contributors please add skywinder for docs

### CODE REVIEW

**Comment by skywinder** [comment]
@all-contributors please add skywinder for docs

**Comment by Berkmann18** [comment]
It doesn't work because it wasn't fully implemented and there were a few issues about and PRs. Have you looked at those?

**Comment by skywinder** [comment]
>  there were a few issues about and PRs

which issues? can you clarify, what do you mean please?

**Comment by Berkmann18** [comment]
> which issues? can you clarify, what do you mean please?

I'm currently not in the position to crawl through the 2-3 repos where the issues about custom templates (there are at least 2) are but if you look for those terms you should be able to find them.

**Comment by devdev606** [comment]
Thankyou

**Comment by skywinder** [comment]
@Berkmann18 Just want to help  and help you with docs and save time for developers to not be confused with oudated example and save them hours.

I did everything by your guidlinges in PR. 
If yo don't nwwd this, feel free to close it. Cheers/

**Comment by Berkmann18** [comment]
Hi,
I didn't get the chance to look at the exact issues, currently trying to merge and clean-up the few AC repos.
Have you looked at the custom template related issues?
The things you removed aren't really outdated but just underdeveloped (namely to due to pending PRs and the contributors who ventured down that path not pushing their PRs).

**Comment by Berkmann18** [comment]
@skywinder Did you get the chance to look at the relevant issues?

**Comment by tenshiAMD** [comment]
> @skywinder Did you get the chance to look at the relevant issues?

@skywinder Hi there!  May we know if you have checked this comment of @Berkmann18? so we can proceed with this one. Thanks!

**Comment by tenshiAMD** [comment]
I agree to this statement of @Berkmann18,

> The things you removed aren't really outdated but just underdeveloped

@skywinder I do not also think it needs to be remove. Closing this for now.

**Comment by skywinder** [comment]
It's 2 years old  hope it works already.

**Pull request closed without merging**
