### PR TITLE
docs: add ReaLTaiizor & Witcher

### PR DESCRIPTION
**Pull request by Taiizor**
Implementations ReaLTaiizor & Witcher added.

### CODE REVIEW

**Review by hriziya — APPROVED** [review]
Confirmed both project follows the guidelines and uses all-contributors.

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@Taiizor Hi, please rebase to `master` branch first and make sure all commits are following semantic convention so we can proceed with this PR. Thanks!

**Comment by gr2m** [comment]
> @Taiizor Hi, please rebase to `master` branch first and make sure all commits are following semantic convention so we can proceed with this PR. Thanks!

@tenshiAMD actually we no longer need all the pull request commits to follow the semantic release convention, only the pull request title needs to follow that convention, thanks to the default commit on squash feature that GitHub introduced recently.

@Taiizor it would still be great if you could resolve the conflicts, or create a new PR if that's easier. Or just let us know and we can add the two organizations, if they both still use @all-contributors today

**Comment by tenshiAMD** [comment]
@gr2m it seems like the head branch of this PR is missing that's why I cannot be merged now. I guess we can recreate this PR in a separate one.

**Pull request closed without merging**
