### PR TITLE
chore:  adding @sasjs/core as an implementation project

### PR DESCRIPTION
**Pull request by allanbowe**
Hi!  Great library - we're making use of it in our open source project.  Thought I'd add to the doc site, given you are inviting these kinds of contributions.

**What**:  Updated the implementations page with a reference to sasjs/core

**Why**:  To showcase our adoption of this great library

**How**:  Simply added the link to the bottom of the list with markdown

**Checklist**:

- [ ] Documentation NA
- [x] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Review by hriziya — APPROVED** [review]
Approved as I confirmed all-contributor being used in the given repo.

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@allanbowe Hi, please rebase to `master` branch first so we can proceed with this PR. Thanks!

**Comment by allanbowe** [comment]
Done!

**Review by tenshiAMD — APPROVED** [review]
@allanbowe LGTM! We can merge this one. Thanks! 🎉

**Comment by tenshiAMD** [comment]
@all-contributors please add @allanbowe for docs

**Pull request merged**
