### PR TITLE
fix: unclosed table cell

### PR DESCRIPTION
**Pull request by Ravenclaw-OIer**
The table in the README has an unclosed table cell because it has 5 languages on the first line but 6 languages on the second.

So I added a `<td>` `</td>` that should solve this problem

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Review by Berkmann18 — CHANGES_REQUESTED** [review]
There's no unclosed table cell and your changes are completely useless.

**Comment by Ravenclaw-OIer** [comment]
@Berkmann18 There are, the rightermost table cell is **not closed**.

See this screenshot:

**Comment by Berkmann18** [comment]
So you mean, there's just a missing cell, the table itself is closed (no missing opening/closing tags) and I don't see the point in adding an empty cell when this table is outdated since we moved to Crowdin-based translations which has more languages.

**Comment by Ravenclaw-OIer** [comment]
Oh, I see. Thx for your time.

**Comment by Ravenclaw-OIer** [comment]
Though it is ugly...

**Comment by Berkmann18** [comment]
> Though it is ugly...

I agree that it's not visually appealing.

**Pull request closed without merging**
