### PR TITLE
docs(implementations): add `educatyeducate/respoui`

### PR DESCRIPTION
**Pull request by e-coders**
I've added respo ui to who's using it list.

### CODE REVIEW

**Comment by e-coders** [comment]
@all-contributors add @e-coders for doc

**Comment by Berkmann18** [comment]
Please, fix the PR to get the checks to pass.

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
> Please, fix the PR to get the checks to pass.

@e-coders please Hi, as @Berkmann18 suggested, please resolve your PR to get the checks to pass. Thanks! :tada:

**Review by tenshiAMD — APPROVED** [review]
@e-coders LGTM! We can merge this one after all checks pass. Thanks! :tada:

**Comment by e-coders** [comment]
> Please, fix the PR to get the checks to pass.

I didn't looked this comment. Well, I think PR is now fixed by @tenshiAMD ?

**Comment by tenshiAMD** [comment]
> I didn't looked this comment. Well, I think PR is now fixed by @tenshiAMD ?

@e-coders yes I fixed it

**Comment by e-coders** [comment]
> > I didn't looked this comment. Well, I think PR is now fixed by @tenshiAMD ?
> 
> @e-coders yes I fixed it

Thank you!

**Comment by Saschaym** [comment]
ashishagarwal2023:patch-1

**Comment by ashishagarwal2023** [comment]
Hm, yes?

**Pull request merged**
