### PR TITLE
updated build Emoji

### PR DESCRIPTION
**Pull request by krishnadevz**
* I added build imogi for working on projects use*

**What**:
* I added build imogi for working on projects use*

**Why**:
* it is use for showing we are building/working on something

**How**:
* just use it from `WIN+;` key in windows then you are good to go

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [x] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Comment by Berkmann18** [comment]
How would that differ from the other contribution categories?

**Comment by krishnadevz** [comment]
@Berkmann18 basically we can use that imogi for showing we are building/working on something others didn't used that imogi yet so this is the good use

**Comment by Berkmann18** [comment]
Hmm, FYI, it's emoji, not emogi :wink:.

I understand the meaning behind that emoji however I fail to see how it would be different from the any of [28 categories](https://allcontributors.org/docs/en/emoji-key).
Like, a project you would work on could involve: design, coding, testing, ideas, maintenance or others (depending on what _exactly_ you do); in such cases, you'll have the contribution types for all of those.

Here's an [example of project I work on](https://github.com/Berkmann18/json-fixer#contributors):
image

**Comment by Berkmann18** [comment]
So, how is it different from the 30 other categories?

**Pull request closed without merging**
