### PR TITLE
docs(french): added French

### PR DESCRIPTION
**Pull request by Berkmann18**
I added the French translation of this repo.

### CODE REVIEW

**Comment by jakebolam** [comment]
@Berkmann18 thank you!

Sorry there are conflicts with the all-contributors addition. If you want to drop them from this PR we will get the bot to add them for you.

**Comment by jakebolam** [comment]
@all-contributors please add Berkmann18 for doc and translation

**Comment by jakebolam** [comment]
@all-contributors please add Berkmann18 for doc and translation

**Comment by Berkmann18** [comment]
Sure, I'll resolve them.

**Pull request merged**
