### PR TITLE
docs(implementations): add InstaGrabber

### PR DESCRIPTION
**Pull request by austinhuang0131**
**What**: Adding my project to the "who's using it?" list.

**Why**: Methinks it's adequate enough to be added to the list. Though, I would strongly suggest if there are some rules being applied to the list. Could be the amount of stars or if the table is nice, etc etc.

**How**:

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [ ] Added myself to contributors table. (Personally don't think it's needed, but go ahead)

### CODE REVIEW

**Comment by Berkmann18** [comment]
We could indeed have rules like those for what goes on the list, that's someone you could suggest on the Slack channel and see what others say about it.

**Review by Berkmann18 — APPROVED** [review]

**Comment by Berkmann18** [comment]
@all-contributors Please add @austinhuang0131 for docs

**Comment by austinhuang0131** [comment]
Noted. Might come up with some sort of rules later.

oh btw this isn't merged

**Comment by Berkmann18** [comment]
> oh btw this isn't merged

Seems like I can't get around the fact that SPR is blocking it due to the commit title you used (which can normally be overridden, but not here).

**Comment by chr688** [comment]
[](https://twitter.com/whatsapp/status/1314334244810878976?s=21)

**Review by chr688 — APPROVED** [review]

**Comment by Cosxxxx** [comment]
- - [CodeScan](https://github.com/actions/setup-node/actions/workflows/codescan-analysis.yml)

**Comment by Cosxxxx** [comment]
****

**Pull request closed without merging**
