### PR TITLE
style: 💄 improve footer/language dropdown/search bar/nav bar

### PR DESCRIPTION
**Pull request by sirpeas**
✅ Closes: #155

**What**:
- Improve language dropdown according to general docs styling
- Add proper responsive styles for language dropdown for better UX on mobile devices
- Add minimalistic styles for footer
- Add background for a search bar and make a magnifier icon more lighter

**Why**:
- Because of #155 

**Checklist**:
- [x] Documentation
- [x] Ready to be merged
- [ ] Added myself to contributors table.

According to style search results, in my opinion, it's okay how it is right now.

### CODE REVIEW

**Comment by sirpeas** [comment]
@all-contributors please update sirpeas for code

**Comment by sirpeas** [comment]
@all-contributors please add sirpeas for code

**Comment by sirpeas** [comment]
I thought there is a separate command (not listed in the documentation), for updating. I think it's worth mentioning.

**Comment by jakebolam** [comment]
Thank you @sirpeas this is great 🚀

**Pull request merged**
