### PR TITLE
Added link to French (Français) documentations in Korean documentations

### PR DESCRIPTION
**Pull request by dance2die**
I have added link to French (Français) documentations in Korean documentations.

## Additional Comment
Maybe there should be a better way to keep these headers in sync?

### CODE REVIEW

**Comment by jakebolam** [comment]
@dance2die we're planning to move all the documentation to the website in #142, to solve this inconsistency problems

**Comment by dance2die** [comment]
Thank you @Berkmann18  & @jakebolam.

Since there is a plan to migrate for the single source of truth, should I close this issue?

**Comment by Berkmann18** [comment]
@dance2die In the meantime, feel free to have a look at https://github.com/all-contributors/all-contributors/issues/143 and contribute to https://crowdin.com/project/all-contributors.

**Comment by dance2die** [comment]
> @dance2die In the meantime, feel free to have a look at #143 and contribute to https://crowdin.com/project/all-contributors.

Thank you @Berkmann18 for the link~

**Comment by Berkmann18** [comment]
You're welcome :).

**Pull request closed without merging**
