### PR TITLE
Update implementations.md

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
**What**: Added my project to implementations.md

**Why**: Lets users know that my project also follows all-contributors specification.

**How**: Added a line in implementations.md

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [x] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Review by hriziya — APPROVED** [review]
Approved as I confirmed all-contributor in the given repo.

**Comment by vedantmgoyal2009** [comment]
@all-contributors please approve.

**Comment by gr2m** [comment]
please add to the end of the list, not the top

**Comment by vedantmgoyal2009** [comment]
Can you please merge it? I've deleted the fork so I will make another PR for the refactor.

**Comment by gr2m** [comment]
Please create a new PR

**Pull request closed without merging**
