### PR TITLE
feat: add a11y contribution type

### LINKED ISSUE #320: New Accessibility (a11y) emoji key
**Is your feature request related to a problem? Please describe.**

On https://github.com/theodo/falco, we are seeing a few contributors reporting a11y issues and/or pushing a11y-related pull requests. I feel like those contributions should be properly rewarded by a specific emoji key.

**Describe the solution you'd like**

A new emoji key, called `a11y` or `accessibility`:

Emoji/Type | Represents | Comments
:---: | :---: | :---:
♿️ <br /> `a11y` | Accessibility | Reporting or working on accessibility issues

**Describe alternatives you've considered**

I’m not convinced by my choice of emoji, here are a few other suggestions: 🕊🙌✨

### PR DESCRIPTION
**Pull request by phacks**
**What**: Add `a11y` (Accessibility) contribution type.

**Why**: Discussed in all-contributors/all-contributors#320

**How**: Added a new contribution type in the emoji key

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Comment by gr2m** [comment]
@all-contributors please add @phacks for doc

**Comment by phacks** [comment]
> Also, don't forget to update the https://github.com/all-contributors/all-contributors-bot repo as well.

@Berkmann18 what should I update in that repo?

**Comment by Berkmann18** [comment]
@phacks [This file](https://github.com/all-contributors/all-contributors-bot/blob/master/src/tasks/processIssueComment/utils/parse-comment/index.js).

**Comment by phacks** [comment]
@Berkmann18 Awesome, thanks! I created the related PR: https://github.com/all-contributors/all-contributors-bot/pull/259

**Pull request merged**
