### PR TITLE
[WIP] Replace emoji in title to aliases

### PR DESCRIPTION
**Pull request by ewnd9**
Probably it could help to https://github.com/kentcdodds/all-contributors/pull/22#issuecomment-191134970 and https://github.com/kentcdodds/all-contributors/pull/22#issuecomment-191260240.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for the PR! For a visual diff (at least on my machine):

Before:

screen shot 2016-03-02 at 8 39 12 am

After:

screen shot 2016-03-02 at 8 39 05 am

Personally, I like the before, but I guess it's pretty different on other people's machines...

**Comment by kentcdodds** [comment]
Hmmm, yeah, you're probably right. I preferred emoji because it's less github specific, but maybe that shouldn't really matter... :-)

**Comment by kentcdodds** [comment]
I'm open to thoughts from others

**Comment by ewnd9** [comment]
I feel like I need to copy my comment from #22 so it won't be missed by others

"I think it would be nice to always stick to ":emoji:" anyways for better accessibility @kentcdodds 

Example: 
image"

**Comment by Jameskmonger** [comment]
I get coloured emojis on my machine now, but they are half the height of the title @ewnd9

**Comment by kentcdodds** [comment]
Yeah, that's what I tried to highlight in my diff. Honestly it's probably fine though...

**Comment by jfmengels** [comment]
image
Same as @Jameskmonger: colored, but small.

**Comment by kentcdodds** [comment]
Yeah, basically I think that the current solution leaves rendering the emoji up to the operating system you're using and the new solution hands over the responsibility of rendering emoji to GitHub's emoji icons.

I would generally prefer to leave rendering up to the OS, but I'm open.

**Comment by ewnd9** [comment]
Please consider also that size of emoji image on github could be adjusted to heading by simple css but emoji support is pretty tricky on windows and linux (related article ["Emoji on Linux"](http://probablement.net/txt/emojilinux)).

Probably there should be some statement from github with recommendations about usage Unicode characters vs ":emoji:" fallbacks

Btw, I'm using [Emoji Cheatsheet](https://chrome.google.com/webstore/detail/emoji-cheatsheet-for-gith/nojknakoailnpbjlmfkpbbhoodlolfbh?utm_source=chrome-app-launcher-info-dialog) chrome extension to lookup emoji aliases

**Comment by jfmengels** [comment]
Nothing to do with the title, but using `:foo:` instead of the corresponding emoji allows you to write the emoji, instead of having to copy/paste the emoji from somewhere. Or at least that's what I do but I think I missed the whole emoji explosion for some reason.

**Comment by MatheusRV** [comment]
In windows you could open emoji table using Windows Key (right of ctrl) + dot (.)

**Comment by Berkmann18** [comment]
@ewnd9 Mind updating the PR?

**Comment by ewnd9** [comment]
I think it lost its relevance. Emoji are slowly rolling out to Linux

**Pull request closed without merging**
