### PR TITLE
fix: prevent shrinking title icons on the homepage

### PR DESCRIPTION
**Pull request by baikho**
**What**:
Fix to prevent shrinking title icons on the homepage https://allcontributors.org/, when the `h5` next to it spans over 2 or more lines. This is visible on the "emoji key" icon when narrowing the browser or looking on a mobile device.

**Why**:
Fix the distorted styling.

**How**:
Added `flex: 0 0 80px;` to the `.title-icon` class:

**Checklist**:

- [ ] Documentation
- [ ] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

**Before / After:**

Screenshot 2020-04-26 at 20 20 24

Screenshot 2020-04-26 at 20 33 17

### CODE REVIEW

**Comment by baikho** [comment]
Just a note on this, it wasn't apparent to me whether this CSS was compiled or not. Please let me know how to do so if that is the case.

**Comment by Berkmann18** [comment]
The preview link (https://deploy-preview-387--allcontributors-org.netlify.app/) doesn't seem to show any difference compared to https://allcontributors.org when testing both on simulated devices.
I only see the shrunk icon on some tablets (namely iPad Air, Galaxy Tab 2 10.1 and Kindle Fire HD 7") and I'm not sure why I'm not seeing your change's effect.
@tbenning Any ideas?

**Comment by baikho** [comment]
Hmm, just curious as to why that link mentions https://deploy-preview-387--allcontributors-org.netlify.app/ which seems to point to PR #387, but this PR is #388 🤔.

**Comment by Berkmann18** [comment]
@all-contributors please add @baikho for bug fix

**Pull request merged**
