### PR TITLE
docs: add important steps for installation

### PR DESCRIPTION
**Pull request by tenshiAMD**
**What**: I added important steps for installation since I noticed it is missing and it is not easy to find the solutions.

**Why**: This will help others with their setup.

**How**: Update the installation section, added important steps

**Checklist**:

- [x] Documentation
- [x] Ready to be merged 
- [x] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Comment by tenshiAMD** [comment]
@all-contributors please add @tenshiAMD for doc

**Comment by tenshiAMD** [comment]
This is also a potential fix for [this issue](https://github.com/all-contributors/all-contributors/issues/613).

**Comment by tenshiAMD** [comment]
@hriziya Please review. Thank you.

**Comment by tenshiAMD** [comment]
@Berkmann18 Please review. Thank you.

**Review by Berkmann18 — APPROVED** [review]
Awesome, thank you.

**Pull request merged**
