### PR TITLE
docs: Add Discord.js-Bot-Template in the "who's using it" list

### PR DESCRIPTION
**Pull request by King-BR**
**What**: Add my project in implementations.md

**Why**:

**How**:

**Checklist**:

- [x] Documentation N/A
- [x] Ready to be merged 
- [x] Added myself to contributors table.  N/A
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

### CODE REVIEW

**Review by hriziya — APPROVED** [review]
Approved as the repo is using all-contributor.

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@King-BR Hi, please rebase first so we can proceed with this PR. Thanks!

**Review by tenshiAMD — APPROVED** [review]
@King-BR LGTM! We can merge this one. Thanks! :tada:

**Comment by tenshiAMD** [comment]
@all-contributors please add @King-BR for doc

**Pull request merged**
