### PR TITLE
fix: show Algolia logo on search dropdown

### PR DESCRIPTION
**Pull request by sinchang**
will break style when hover the logo

image

refs: 

- https://github.com/facebook/Docusaurus/issues/1239 
- #201

### CODE REVIEW

**Comment by jakebolam** [comment]
Good spot @sinchang

**Comment by jakebolam** [comment]
@sinchang is this ready to be reviewed? Do we need to bump Docusaraus

**Comment by sinchang** [comment]
@jakebolam Need to wait for a new version of Docusaraus. already sent a request in https://github.com/facebook/Docusaurus/pull/1240#issuecomment-466770996.

**Comment by jakebolam** [comment]
Thanks @sinchang

**Pull request merged**
