### PR TITLE
perf(images): optimize images

### PR DESCRIPTION
**Pull request by Berkmann18**
Courtesy of @imgbot in https://github.com/Berkmann18/all-contributors/pull/1:
> Image file size has been reduced by **33%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /other/logo-square.png | 15.46kb | 8.82kb | 42.95% |
| /other/logo-full.png | 37.35kb | 25.43kb | 31.92% |
| /other/logo-square-transparent.png | 32.57kb | 22.42kb | 31.15% |
| /other/logo-full-transparent.png | 47.40kb | 32.67kb | 31.08% |
| | | | |
| **Total :** | **132.77kb** | **89.34kb** | **32.72%** |
</details>

> ---

> [📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MatheusRV** [comment]
Amazing bot :)

**Comment by Berkmann18** [comment]
@MatheusRV Indeed, aside from the lack of commit convention awareness (cf https://github.com/dabutvin/ImgBot/issues/232).

@codimiracle What do you mean?

**Comment by codimiracle** [comment]
i think it will be a good feature for some big picture-based repo (eg. designer repo) .

**Comment by Berkmann18** [comment]
@codimiracle Indeed, however, @ImgBotApp only compress the images within the repo so all the avatars and such won't be touched.

**Comment by jakebolam** [comment]
With #172 we will get image optimization too.

Do you think it would be better to leave the raw images in the repo? Or compress them?

**Comment by Berkmann18** [comment]
@jakebolam Well, unless there's a negative impact from the imgbot optimised one, I don't think it would be bad to keep them but I don't mind leaving the optimisation to only netlify (although I don't know how good its optimisation system is).

**Comment by jakebolam** [comment]
@Berkmann18 https://imgbot.net/winning/ has been installed on the org 🎉

**Comment by jakebolam** [comment]
I believe Netlify handles this for us too :)

**Comment by Berkmann18** [comment]
Yeah, it can process resources which is great so I guess this PR isn't needed anymore.

**Pull request closed without merging**
