### PR TITLE
fix: jagged white edge around the logo

### LINKED ISSUE #420: Logo has jagged white edge
**Describe the bug**
The logo used in the [README.md](https://github.com/all-contributors/all-contributors/blob/master/README.md) has a jagged white border, easily spotted with a different color background.

**To Reproduce**
1. Change GitHub's background color (with something like [Dark Reader](https://darkreader.org/) or [a Stylus theme](https://github.com/StylishThemes/GitHub-Dark))
1. Go to the [README.md](https://github.com/all-contributors/all-contributors/blob/master/README.md)
1. Look at the image
1. See the white jagged edge around it

**Expected behavior**
The image should have no white edge, so as to look clean and consistent, regardless of device, screen size or background color.

**Screenshots**

**Additional context**
Image in question is at [`docs/assets/logo-full-transparent.png`](https://github.com/all-contributors/all-contributors/blob/master/docs/assets/logo-full-transparent.png)

This is a tiny detail, but I decided to point it out, so that you're aware of it.

I did manage to fix it in the README by simply copying the path to the SVG used in [allcontributors.org](https://allcontributors.org/) ([`https://d33wubrfki0l68.cloudfront.net/02a655fd7b0c5dae117b57bfde67f8850bb23226/e2f0c/img/logo.svg`](https://d33wubrfki0l68.cloudfront.net/02a655fd7b0c5dae117b57bfde67f8850bb23226/e2f0c/img/logo.svg)) and using it instead, and it didn't have the white border, but as the image used here is actually stored in the repo itself, I'm not sure if that'd be an acceptable fix.

### PR DESCRIPTION
**Pull request by MicaelJarniac**
**What**:

Fixes #420 

**Why**:

To make the logo displayed on the README.md more clean and consistent across different backgrounds, not just white.

**How**:

By replacing the reference to `docs/assets/logo-full-transparent.png` with the same SVG logo used on [allcontributors.org](https://allcontributors.org) [`https://d33wubrfki0l68.cloudfront.net/02a655fd7b0c5dae117b57bfde67f8850bb23226/e2f0c/img/logo.svg`](https://d33wubrfki0l68.cloudfront.net/02a655fd7b0c5dae117b57bfde67f8850bb23226/e2f0c/img/logo.svg)

**Checklist**:

- [ ] Documentation N/A
- [x] Ready to be merged 
- [ ] Added myself to contributors table. 
[Bot Usage](https://allcontributors.org/docs/en/bot/installation#4-update-your-contributing-documentation)

This is one way of fixing the issue reported in issue #420, but as mentioned in that issue, this might not be the cleaner, most desirable, way of going about it.

### CODE REVIEW

**Comment by MicaelJarniac** [comment]
> I think switching to an SVG image is indeed a good idea, however it should be part of the repo itself so it doesn't rely on an external source.

Done! It's now a file stored locally on the repo, alongside the `logo-full-transparent.png`, called `logo-full.svg` (I omitted the `transparent` at the end because I believe it being an SVG file implies that, in a way.

The previous file is still there.

And the reference to it on the README.md has been replaced to the new local SVG logo.

**Comment by MicaelJarniac** [comment]
> Looking good so far. I've got some questions surrounding the performance side of things.
> 
> 1. Do you think it would be possible to remove the redundant layer(s)?
> 2. Have you optimised the SVG?

I have absolutely no idea. I've never dealt with this kind of file before. But it's the one used for the logo on https://allcontributors.org.



So I think it's either fine to use it here as well, or it should also be updated on the website.

But again, I've never played with this kind of file, so I really don't know for sure.

**Comment by Berkmann18** [comment]
It's fine, SVG isn't my forté either, it's mainly things that came to mind when I contributed to [simple-icons](https://github.com/simple-icons/simple-icons) which recommends contributors to compress SVGs using SVGO or SVGOMG and removing code like `<g>` and `</g>` which AFAIK don't change anything as far as the rendering and output goes,

**Comment by MicaelJarniac** [comment]
> It's fine, SVG isn't my forté either, it's mainly things that came to mind when I contributed to [simple-icons](https://github.com/simple-icons/simple-icons) which recommends contributors to compress SVGs using SVGO or SVGOMG and removing code like `<g>` and `</g>` which AFAIK don't change anything as far as the rendering and output goes,

I've just run it against [SVGOMG](https://jakearchibald.github.io/svgomg/), and removed the `<g>` and `</g>` tags, but it dropped only from **6.99k** to **6.69k**, which I think isn't a lot.

I could get it to *5.44k*, but that'd slightly move things around, and I'd rather not. Here's a GIF showing that (watch closely):

GIF

The **6.69k** version seems to have no quality loss.

I'll update my branch with it.

**Comment by Berkmann18** [comment]
@all-contributors Please add @MicaelJarniac for bug

**Review by mary-doc — COMMENTED** [review]
Give explicit approval

**Pull request merged**
